export enum Limits {
    MIN_USERNAME_LENGTH = 5,
    MAX_USERNAME_LENGTH = 15,

    MIN_PASSWORD_LENGTH = 5,
    MAX_PASSWORD_LENGTH = 15,

    MIN_FULLNAME_LENGTH = 6,
    MAX_FULLNAME_LENGTH = 30,

    MIN_EMAIL_LENGTH = 6,
    MAX_EMAIL_LENGTH = 30,

    HASH_ROUNDS = 10,

    MAX_OFFICE_ROWS = 10,
    MIN_OFFICE_ROWS = 1,

    MAX_OFFICE_COLS = 10,
    MIN_OFFICE_COLS = 1,

    MAX_OFFICE_DESK_PER_COL = 6,
    MIN_OFFICE_DESK_PER_COL = 1,

    MAX_OFFICE_DESK_PER_ROW = 6,
    MIN_OFFICE_DESK_PER_ROW = 1,
    
    MIN_ROW_COL_DISTANCE = 1.5,
    MAX_ROW_COL_DISTANCE = 3,

    MIN_OFFICE_NAME_LENGTH = 6,
    MAX_OFFICE_NAME_LENGTH = 30,

    MIN_PROJECT_NAME_LENGTH = 5,
    MAX_PROJECT_NAME_LENGTH = 15,

    MIN_PROJECT_DESCRIPTION_LENGTH = 5,
    MAX_PROJECT_DESCRIPTION_LENGTH = 60,

    COVID_URL = 'https://coronavirus-19-api.herokuapp.com/'
}